# Generated by Django 2.1.3 on 2018-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181118_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
